<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE articulos [
    <!ELEMENT articulos (articulo)*>
    <!ELEMENT articulo (identificacion, nombre)>
    <!-- ATENTO AL ASTERISCO, PUEDE HABER MAS DE 1 -->
    <!ELEMENT identificacion (#PCDATA | codigo | id)*>
    <!ELEMENT codigo (#PCDATA)>
    <!ELEMENT id (#PCDATA)>
    <!ELEMENT nombre (#PCDATA)>
]>
<articulos>
    <articulo>
        <identificacion>
            Quedan 10 unidades
            <codigo>123jhasjdb</codigo>
        </identificacion>
        <nombre>tijeras</nombre>
    </articulo>
    <articulo>
        <identificacion>
            <codigo>SIE478</codigo>
            <id>juerasdaw</id>
            No hay stock
        </identificacion>
        <nombre>sierra</nombre>
    </articulo>
</articulos>